#pragma config(Motor,  port1,           rightWheel1,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightWheel2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightWheel3,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftWheel2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftWheel3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           catapult1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapult2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           catapult3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftWheel1,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

void setWheelSpeeds (int left, int right) {
  setLeftWheelSpeeds(left);
  setRightWheelSpeeds(right);
}

void setLeftWheelSpeed (int speed) {
  motor[leftWheel1] = speed;
  motor[leftWheel2] = speed;
  motor[leftWheel3] = speed;
}

void setRightWheelSpeed (int speed) {
  motor[rightWheel1] = speed;
  motor[rightWheel2] = speed;
  motor[rightWheel3] = speed;
}

void setCatapultSpeed (int speed) {
  motor[cataput1] = speed;
  motor[cataput2] = speed;
  motor[cataput3] = speed;
}

//tank drive
void tankDrive () {
  //left wheels
  if(abs(vexRT(Ch3))<10) //deadbands
    setLeftWheelSpeed(0);
  else
    setLeftWheelSpeed(vexRT(Ch3));

  //right wheels
  if(abs(vexRT(Ch2))<10) //deadbands
    setRightWheelSpeed(0);
  else
    setRightWheelSpeed(vexRT(Ch2));
}

void intake() {
  if(VexRT(Btn5U))
    motor[intake] = 127;
  else if(VexRT(Btn5D))
    motor[intake] = -127;
  else
    motor[intake] = 0;
}

void pre_auton() {
  bStopTasksBetweenModes = true;

}

int catapultDelay = 20; //delay for cycle to start reading sensor
task catapultKick() {
  while(true) {
    if(VexRT(Btn6U))
      setCatapultSpeed(127);
      wait1Msec(catapultDelay); //May not need
      while(!SensorValue[rightCatapult])
        setCatapultSpeed(127);
      setCatapultSpeed(0);
    wait1Msec(30);
  }
}

int ballLoadDelay = 300;
task catapultKickUserLoad() {
  while(true) {
    setCatapultSpeed(127);
    wait1Msec(catapultDelay); //May not need
    while(!SensorValue[rightCatapult] || !SensorValue[leftCatapult])
      setCatapultSpeed(127);
    setCatapultSpeed(0);
  wait1Msec(ballLoadDelay);
  }
}

task autonomous() {

}

task usercontrol() {

  while (true) {
    if(VexRT(Btn6U))
      startTask(catapultKick);


    tankDrive();

    //Anywhere from 25-50 Msec pause to prevent cortex overload
    wait1Msec(30);
  }
}
