#pragma config(Motor,  port1,           rightWheel1,   tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightWheel2,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           rightWheel3,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           leftWheel2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           leftWheel3,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           catapult1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           catapult2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           catapult3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          leftWheel1,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/** Sets the speeds of all wheels. **/
void setWheelSpeeds (int left, int right) {
  setLeftWheelSpeeds(left);
  setRightWheelSpeeds(right);
}

/** Sets the speeds of all the left wheels. **/
void setLeftWheelSpeed (int speed) {
  motor[leftWheel1]   = speed;
  motor[leftWheel2]   = speed;
  motor[leftWheel3]   = speed;
}

/** Sets the speeds of all the right wheels. **/
void setRightWheelSpeed (int speed) {
  motor[rightWheel1]  = speed;
  motor[rightWheel2]  = speed;
  motor[rightWheel3]  = speed;
}

/** Sets all the catapult motors. **/
void setCatapultSpeed (int speed) {
  motor[cataput1]     = speed;
  motor[cataput2]     = speed;
  motor[cataput3]     = speed;
}

/** Controlls the drivebase. **/
void tankDrive () {

  //left wheels
  if(abs(vexRT(Ch3))<10) //deadbands
    setLeftWheelSpeed(0);
  else
    setLeftWheelSpeed(vexRT(Ch3));

  //right wheels
  if(abs(vexRT(Ch2))<10) //deadbands
    setRightWheelSpeed(0);
  else
    setRightWheelSpeed(vexRT(Ch2));
}

/** Controlls the intake for balls. Currently not toggle, can easialy be. **/
void intake() {
  if(VexRT(Btn5U))
    motor[intake] = 127;
  else if(VexRT(Btn5D))
    motor[intake] = -127;
  else
    motor[intake] = 0;
}

/** Pre autonomous task (who actually uses this?).
May put in some pretty flashing indicator lights **/
void pre_auton() {
  bStopTasksBetweenModes = true;

}

/** Controlls the cataptult for regular field use **/
int catapultDelay = 20; //delay for cycle to start reading sensor
task catapultKick() {
  while(true) {
    if(VexRT(Btn6U))
      setCatapultSpeed(127);
      wait1Msec(catapultDelay); //May not need
      while(!SensorValue[rightCatapult])
        setCatapultSpeed(127);
      setCatapultSpeed(0);
    wait1Msec(30);
  }
}

/** Controlls the catapult for driver loads and autonomous **/
int ballLoadDelay = 1000; //Delay for the ball to be loaded by human driver.
task catapultKickUserLoad() {
  while(true) {
    setCatapultSpeed(127);
    wait1Msec(catapultDelay); //May not need
    while(!SensorValue[rightCatapult] || !SensorValue[leftCatapult])
      setCatapultSpeed(127);
    setCatapultSpeed(0);
  wait1Msec(ballLoadDelay);
  }
}

/** Autonomous task - 15 seconds **/
task autonomous() {
  ClearTimer(T1);
  startTask(catapultKickUserLoad);
  while(time1[T1]<5000) {}
  stopTask(catapultKickUserLoad);
  setWheelSpeeds(127,127);
  wait1Msec(1100);
  setWheelSpeeds(0,0);
}

/*
ch3               = run all right side motors
ch2               = run all left side motors
Btn5U             = 127 intake
Btn5D             = -127 intake
Btn6U tapped      = run catapults once in a cycle
Btn6U holded down = full auto
Btn8D             = run driver load shooter (basically full auto) - don’t have to run intake
Btn8U             = stop driver load shooter
Btn7D             = auto align with gyro (not necessary yet)
*/
/** Usercontrol task **/
task usercontrol() {
  while (true) {
    if(VexRT(Btn6U))
      startTask(catapultKick);

    if(VexRT(Btn8D))
      startTask(catapultKickUserLoad);
    else if(VexRT(Btn8U))
      stopTask(catapultKickUserLoad);

    //Add Gyro - 7D

    tankDrive();

    intake();

    //Anywhere from 25-50 Msec pause to prevent cortex overload
    wait1Msec(30);
  }
}
